services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Con este cambio permite que al editar cualquier archivo fuera de docker, el cambio se implemente en docker
    ports:
      - '80:80'